formatting and fixed the ci issue

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,10 +11,10 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: 📥 Checkout code
+      - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: ⚙️ Set up Go
+      - name: Set up Go
         uses: actions/setup-go@v4
         with:
           go-version: 1.24.2
@@ -29,7 +29,7 @@ jobs:
         run: make build
 
       - name: List bin contents
-        run: ls -lh bin || echo "❌ bin/ not found"
+        run: ls -lh bin || echo " bin/ not found"
 
       - name: Upload binary
         uses: actions/upload-artifact@v4
@@ -37,7 +37,7 @@ jobs:
           name: overlap-avalara
           path: bin/overlap-avalara
 
-      - name: 🧹 Clean bin folder (explicit rm fallback)
+      - name:  Clean bin folder (explicit rm fallback)
         run: |
           echo "Cleaning bin manually..."
           rm -rf bin
